### ISSUE TITLE
No error is thrown when the config file doesnt find the variable

### ISSUE THREAD

**Issue by barzilay** [spriteCloud/lapis-lazuli#31]
**Actual**

Using _env('config_variable')_ doesnt give an error if it doesnt find the env and returns an empty value

**Expected**

- Throw an error if the config file that you request isnt found
- Dont return an empty value and proceed

**Comment by sjieg** [comment]
./LL/world/config.rb:391
```
return value
```
./LL/world/config.rb:318
```
value = default
```
./LL/world/config.rb:312
```
def var_from_env(var, default=nil)
```
So, because the default for `default` is nil, the method will return `nil` if it failed.

To override this we can simply add a `error('...') if value === nil` before returning the value. 
First we should check what the impact of this change will be.

**Comment by osteenbergen** [comment]
```env``` function should use the same structure as the ```config``` function. We need to know if the default was used and set to nil or not.

```ruby
def env(variable=false, default=(no_default_set=true;nil))
```

Now you can easily change the return from
```ruby
return self.config("#{@env}.#{variable}",default)
```
to
```ruby
result = self.config("#{@env}.#{variable}",default)

if no_default_set == true and result.nil?
    raise "Unknown environment variable '#{variable}' and no default given!"
end

return result
```
